# Generated by Django 6.0.1 on 2026-01-16 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='submission',
            name='hallucination_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='submission',
            name='latency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='submission',
            name='token_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AgentProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_system_prompt', models.TextField()),
                ('base_retrieval_config', models.JSONField(default=dict)),
                ('tool_definitions', models.JSONField(blank=True, default=list)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_info', to='core.problem')),
            ],
        ),
        migrations.CreateModel(
            name='AgentTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_query', models.TextField()),
                ('expected_response', models.TextField()),
                ('ground_truth_context', models.TextField(blank=True, null=True)),
                ('agent_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='core.agentproblem')),
            ],
        ),
    ]
