# Generated by Django 6.0.1 on 2026-01-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_submission_accuracy_submission_hallucination_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
